### ISSUE TITLE
panic on get services

### ISSUE THREAD

**Issue by plorenz** [openziti/sdk-golang#486]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x20513dc]

goroutine 250 [running]:
github.com/openziti/sdk-golang/edge-apis.(*ApiSession).GetAccessHeader(...)
        /home/plorenz/go/pkg/mod/github.com/openziti/sdk-golang@v0.22.17/edge-apis/authwrapper.go:57
github.com/openziti/sdk-golang/edge-apis.(*ApiSession).AuthenticateRequest(0x393e214?, {0x40aeda0, 0xc0024e7780}, {0x0?, 0x0?})
        /home/plorenz/go/pkg/mod/github.com/openziti/sdk-golang@v0.22.17/edge-apis/authwrapper.go:69 +0x1c
github.com/go-openapi/runtime/client.(*request).buildHTTP(0xc0024e7780, {0x3997e42, 0x10}, {0x404d588, 0x1}, 0x0?, {0x0, 0x0}, {0x406b740, 0x0})
        /home/plorenz/go/pkg/mod/github.com/go-openapi/runtime@v0.26.2/client/request.go:279 +0xc66
github.com/go-openapi/runtime/client.(*Runtime).createHttpRequest(0xc001c01420, 0xc0010fa000)
        /home/plorenz/go/pkg/mod/github.com/go-openapi/runtime@v0.26.2/client/runtime.go:420 +0x425
github.com/go-openapi/runtime/client.(*Runtime).Submit(0xc001c01420, 0xc0010fa000)
        /home/plorenz/go/pkg/mod/github.com/go-openapi/runtime@v0.26.2/client/runtime.go:440 +0x6d
github.com/openziti/edge-api/rest_client_api_client/service.(*Client).ListServices(0xc000c0a4e0, 0xc001708c60?, {0x406b740?, 0x0}, {0x0, 0x0, 0x2000107?})
        /home/plorenz/go/pkg/mod/github.com/openziti/edge-api@v0.26.8/rest_client_api_client/service/service_client.go:268 +0x337
github.com/openziti/sdk-golang/ziti.(*CtrlClient).GetServices(0xc0020ca000)
        /home/plorenz/go/pkg/mod/github.com/openziti/sdk-golang@v0.22.17/ziti/client.go:337 +0x113
github.com/openziti/sdk-golang/ziti.(*ContextImpl).refreshServices(0xc001c000e0, 0x0)
        /home/plorenz/go/pkg/mod/github.com/openziti/sdk-golang@v0.22.17/ziti/ziti.go:657 +0x536
github.com/openziti/sdk-golang/ziti.(*ContextImpl).runRefreshes(0xc001c000e0)
        /home/plorenz/go/pkg/mod/github.com/openziti/sdk-golang@v0.22.17/ziti/ziti.go:761 +0x48a
created by github.com/openziti/sdk-golang/ziti.(*ContextImpl).onFullAuth.func1 in goroutine 85
        /home/plorenz/go/pkg/mod/github.com/openziti/sdk-golang@v0.22.17/ziti/ziti.go:878 +0x7b
```

**Comment by plorenz** [comment]
This was fixed, I think in 0.23.0
